Repository emmahsax/emmahsax.github.io, pull requests merged in 2020-06, with the labels that each got.

#242 Add LEGO car
  .github/contributing.md
  _blog_posts/adding-pagination-without-jekyll.md
  _blog_posts/opening-links-in-new-tabs-via-javascript.md
  _blog_posts/time-zones-utc-and-javascript-oh-my.md
  _blog_posts/using-jekyll-paginate-v2.md
  _blog_posts/welcome-to-kenya/jambo.md
  _blog_posts/welcome-to-kenya/kwaheri.md
  _blog_posts/welcome-to-kenya/the-cuisine-and-the-lodging.md
  _blog_posts/welcome-to-kenya/the-game-drives.md
  _includes/elements/404.html
  _layouts/home.html
  _legos/NOTES.md
  _legos/box.md
  _legos/car.md
  _legos/diving-yacht.md
  _legos/dots-picture-frame.md
  _legos/helicopter-adventure.md
  assets/css/_site.scss
Labels: clean up, new content

#251 Update cron user
  .github/workflows/cron.yml
Labels: bug

#252 Determine GH Actions user photo programmatically
  .github/workflows/cron.yml
  .github/workflows/develop.yml
  .github/workflows/release.yml
Labels: bug

#254 Blog post about renaming the master branch
  README.md
  _blog_posts/why-and-how-i-renamed-my-master-branch.md
  _pages/about-me.md
Labels: new content

#255 Fix error rendering dates
  assets/js/external-links.js
  assets/js/show-dates.js
Labels: bug

#256 Update badges
  README.md
  _includes/site/footer.html
Labels: documentation, new content

#259 Nest Interests & Hobbies pages
  Gemfile.lock
  _config.yml
  _includes/elements/email-button.html
  _includes/elements/icon-buttons.html
  _includes/site/header.html
  _layouts/index.html
  _layouts/legos.html
  _legos/box.md
  _legos/car.md
  _pages/about-me.md
  _pages/blog.md
  _pages/index.md
  _pages/interests-and-hobbies.md
  _pages/interests-and-hobbies/legos.md
  _pages/interests-and-hobbies/theatre.md
  _pages/legos.md
Labels: dependencies, enhancement, new content

#261 New versions of gems
  Gemfile.lock
Labels: dependencies

#263 Add more LEGOs
  _legos/NOTES.md
  _legos/dorm-room.md
  _legos/fairground.md
Labels: documentation, new content

#265 Address bugs in switch to CommonMark
  .github/workflows/release.yml
  _config.yml
Labels: bug, clean up

#267 Update fonts; respace blog/lego pages
  Gemfile.lock
  _blog_posts/email-subscriptions-rss-feeds-and-feed-readers.md
  _includes/blog/post.html
  _includes/blog/posts-list.html
  _includes/legos/list.html
  assets/css/_code.scss
  assets/css/_google_fonts.scss
  assets/css/_site.scss
Labels: dependencies, enhancement

#268 Add markdownlint
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/code_of_conduct.md
  .github/contributing.md
  .github/pull_request_template.md
  .github/security.md
  .github/workflows/cron.yml
  .github/workflows/develop.yml
  .github/workflows/release.yml
  Gemfile
  Gemfile.lock
  _blog_posts/adding-bootstrap-to-your-static-content-site.md
  _blog_posts/adding-pagination-without-jekyll.md
  _blog_posts/bootstrap-css-and-icons-in-this-site.md
  _blog_posts/dns-domains-and-personal-websites.md
  _blog_posts/email-subscriptions-rss-feeds-and-feed-readers.md
  _blog_posts/hyphen-versus-em-versus-en-versus-everything-else.md
  _blog_posts/my-time-with-two-jobs.md
  _blog_posts/opening-links-in-new-tabs-via-javascript.md
  _blog_posts/skimp-and-splurge/the-art-of-saving-money.md
  _blog_posts/skimp-and-splurge/three-years-later.md
  _blog_posts/switching-to-jekyll.md
  _blog_posts/time-zones-utc-and-javascript-oh-my.md
  _blog_posts/using-jekyll-paginate-v2.md
  _blog_posts/welcome-to-kenya/the-journey-home.md
  _blog_posts/what-i-learned-being-recruited-to-landmark-forum.md
  _blog_posts/why-and-how-i-renamed-my-master-branch.md
  _blog_posts/why-i-switched-from-circleci-to-github-actions.md
  _blog_posts/why-i-switched-from-travis-ci-to-circleci.md
  _blog_posts/why-tomorrow-isnt-useful.md
  _legos/NOTES.md
  scripts/define_run_variables.sh
  scripts/markdown_linter.sh
  scripts/markdown_toc.rb
  scripts/set_deploy_status_message.sh
Labels: documentation, enhancement

#269 Add jekyll tidy
  Gemfile
  Gemfile.lock
  _config.yml
Labels: dependencies

#270 Create failure deploy message just in case
  scripts/define_run_variables.sh
Labels: bug, tests

#271 Update gems
  Gemfile.lock
Labels: dependencies

#273 Use cache@v2 in GitHub Actions
  .github/workflows/cron.yml
  .github/workflows/develop.yml
  .github/workflows/release.yml
Labels: tests

#274 Slack webhook should be passed in as 'with'
  .github/workflows/cron.yml
  .github/workflows/develop.yml
  .github/workflows/release.yml
Labels: tests
