Repository emmahsax/emmahsax.github.io, pull requests merged in 2021-02, with the labels that each got.

#360 Even more spam protection
  _layouts/contact.html
  assets/js/forms.js
Labels: enhancement

#361 Add more verification
  assets/js/forms.js
Labels: enhancement

#362 Add blog post for contact page
  _blog_posts/adding-html-forms-to-static-sites.md
  assets/js/forms.js
Labels: new content

#363 Make it clear the reCAPTCHA is "required"
  _blog_posts/adding-html-forms-to-static-sites.md
  _layouts/contact.html
  assets/js/forms.js
Labels: bug, enhancement

#364 Pull out inline Javascript to their own files
  _blog_posts/301-redirects-with-static-sites.md
  _blog_posts/adding-html-forms-to-static-sites.md
  _blog_posts/bootstrap-css-and-icons-in-this-site.md
  _blog_posts/opening-links-in-new-tabs-via-javascript.md
  _blog_posts/time-zones-utc-and-javascript-oh-my.md
  _layouts/contact.html
  _layouts/default.html
  _layouts/post.html
  assets/js/activate_feather.js
  assets/js/get_full_year.js
Labels: enhancement

#367 Fix typo as caused by {% raw %}
  _blog_posts/opening-links-in-new-tabs-via-javascript.md
Labels: bug

#365 Pull out inline CSS to external CSS files
  _blog_posts/adding-html-forms-to-static-sites.md
  _blog_posts/switching-from-kramdown-to-commonmark.md
  _includes/blog/post_categorization.html
  _includes/blog/post_summary.html
  _includes/elements/all_posts_button.html
  _includes/elements/disabled_x.html
  _includes/elements/email_button.html
  _includes/elements/github_issue_button.html
  _includes/elements/next_page.html
  _includes/elements/previous_page.html
  _includes/lego_list.html
  _includes/site_navigation.html
  _layouts/blog.html
  _layouts/contact.html
  _layouts/index.html
  _layouts/post.html
  assets/css/_blog.scss
  assets/css/_form.scss
  assets/css/_homepage.scss
  assets/css/_navigation.scss
  assets/css/_pagination.scss
  assets/css/_site.scss
  assets/css/style.scss
  assets/js/forms.js
  pages/404.md
  pages/interests-and-hobbies/theatre.md
Labels: enhancement

#366 Add meta HTML tags to make general HTML more secure
  _blog_posts/4th-of-july-to-party-or-not-to-party.md
  _blog_posts/switching-from-kramdown-to-commonmark.md
  _blog_posts/using-jekyll-paginate-v2.md
  _layouts/contact.html
  _layouts/default.html
  _layouts/post.html
  assets/js/forms.js
  assets/js/show_comments.js
Labels: enhancement

#368 Fix textarea bug
  _layouts/contact.html
Labels: bug

#369 Update Bootstrap, gems, and deploy action
  .github/workflows/main.yml
  Gemfile.lock
  assets/css/bootstrap.min.css
  assets/js/bootstrap.min.js
Labels: dependencies, tests

#370 New version of jekyll-seo-tag
  Gemfile
  Gemfile.lock
Labels: dependencies

#371 Specify for jekyll-seo-tag that we want to prioritize the site title
  Gemfile.lock
  _config.yml
Labels: bug

#375 Fix bug where gifs from Giphy don't show up properly
  _layouts/default.html
  assets/css/_navigation.scss
Labels: bug, enhancement

#376 Use official Javascript linter instead of Code Climate
  .github/contributing.md
  .github/workflows/main.yml
  .gitignore
  .rubocop.yml
  Gemfile
  Gemfile.lock
  README.md
  assets/js/external_links.js
  assets/js/forms.js
  assets/js/get_full_year.js
  assets/js/show_comments.js
  assets/js/show_dates.js
  bin/javascript_linter.sh
  package-lock.json
  package.json
Labels: dependencies, documentation, tests
